# Enable mouse support
set -g mouse on

# Set the prefix to Ctrl + Space
unbind C-b
set -g prefix C-y
bind C-y send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g default-command "exec zsh -l"

# Set the color theme to Catppuccin Mocha
set -g @tmux2k-text "#181825"
set -g @tmux2k-bg-main "#191824"
set -g @tmux2k-bg-alt "#313244"
set -g @tmux2k-black "#181825"
set -g @tmux2k-red "#f38ba8"
set -g @tmux2k-light-red "#eba0ac"
set -g @tmux2k-green "#a6e3a1"
set -g @tmux2k-light-green "#94e2d5"
set -g @tmux2k-blue "#89b4fa"
set -g @tmux2k-light-blue "#89dceb"
set -g @tmux2k-yellow "#fab387"
set -g @tmux2k-light-yellow "#f9e2af"
set -g @tmux2k-purple "#cba6f7"
set -g @tmux2k-light-purple "#f5c2e7"

# Selection highlight colors
set -g mode-style "fg=#{@tmux2k-text}, bg=#{@tmux2k-blue}"

# Window separators
set -g @tmux2k-window-left-sep ""
set -g @tmux2k-window-right-sep ""

# Plugins
set -g @tmux2k-left-plugins "cwd git"
set -g @tmux2k-right-plugins "cpu ram battery time"

# Set plugin colors
set -g @tmux2k-cwd-colors "blue text"
set -g @tmux2k-git-colors "bg_alt purple"
set -g @tmux2k-cpu-colors "bg_alt purple"
set -g @tmux2k-ram-colors "bg_alt purple"
set -g @tmux2k-battery-colors "bg_alt purple"
set -g @tmux2k-time-colors "blue text"

# Military time
set -g @tmux2k-military-time true

# Set CPU and RAM labels
set -g @tmux2k-cpu-usage-label ""
set -g @tmux2k-ram-usage-label ""

# Set theme
set -g @catppuccin_flavour 'mocha'


# set vi-mode
set-window-option -g mode-keys vi

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Make copy mode use vi keys
setw -g mode-keys vi

# Start selection with 'v'
bind -T copy-mode-vi v send-keys -X begin-selection

# Rectangle selection toggle with Ctrl+v
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# Copy selection and exit with 'y'
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enter copy mode with Ctrl+v (always)
bind -n C-v copy-mode -u

# the new planes have the same cwd as the splited plane
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"


# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-dir '/Users/afonsomanata/.tmux/resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'

# makes plugins work
run ~/.tmux/plugins/tpm/tpm
