[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless"

opacity = 0.4
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12


[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

